site_name: CB Training docs
nav:
  - Home: index.md
  - Walkthroughs:
    - APPT Drop Off procedure : apptintake.md
    - Special orders : SpecOrder.md
    - Customer Profiles : CustProfile.md
    - Gift Cards : giftcards.md
    - Attaching customers : attach.md
    - Checking out : LScheckout.md
    - Deposits : deposit.md
    - Texting through Lightstpeed (Ikeono) : ikeono.md
    - Receiving and Purchase Orders : receiving.md
    - Creating and Importing item cards  : itemcards.md
    - Online Bike sale pickups : b2c.md
    - Bike sales  : bikesale.md
    - Returns and finding a receipt : return.md
    - Work Orders Basics : workorder.md
    - Boston E-Bike Vouchers 2024: bostonvoucher.md
    - MassCEC E-Bike Vouchers 2025: massvoucher.md
#   - Opening/Closing procedure ROUGH DRAFT: clopen.md
#   - Annual inventory OUTLINE : annualinv.md

#   - How to find next APPT date
#   - How to create a work order
#   - Creating a work order for a repair
#   - Counting out
#   - Opening register procedures
#   - Using Square - how to ring people up and reconcile the payments in LS



# - Resources:
#    Employee handbook 
#    Attendance - shift start & end, calling out, scheduling time off
#    Breaks
#    Employee purchases
#    Dress code
#    After hours policy
#    PTO and vacation policy



theme: 
  name: readthedocs
  custom_dir: overrides
plugins:
   - glightbox:
      zoomable: true
   - search: