site_name: CB Training docs
nav:
  - Home: index.md
  - Walkthroughs:
    - APPT Intake ROUGH DRAFT: apptintake.md
    - Special orders ROUGH DRAFT: SpecOrder.md
    - Customer Profiles ROUGH DRAFT: CustProfile.md
    - Checking out ROUGH DRAFT: LScheckout.md
    - Deposits ROUGH DRAFT: deposit.md
    - Ikeono chat ROUGH DRAFT: ikeono.md
  - Resources:
    - Employee handbook NODRAFT: handbook.md
theme: readthedocs
