site_name: CB Training docs
nav:
  - Home: index.md
  - Walkthroughs:
    - APPT Drop Off procedure ROUGH DRAFT: apptintake.md
    - Special orders ROUGH DRAFT: SpecOrder.md
    - Customer Profiles ROUGH DRAFT: CustProfile.md
    - Gift Cards ROUGH DRAFT: giftcards.md
    - Attaching customers ROUGH DRAFT: attach.md
    - Checking out ROUGH DRAFT: LScheckout.md
    - Deposits ROUGH DRAFT: deposit.md
    - Texting through Lightstpeed (Ikeono) ROUGH DRAFT: ikeono.md
    - Receiving and Purchase Orders ROUGH DRAFT: receiving.md
    - Creating and Importing item cards  ROUGH DRAFT: itemcards.md
    - Online order pickups ROUGH DRAFT: b2c.md
    - Bike sales ROUGH DRAFT NEED ROB INPUT ON OTD SECTION : bikesale.md
    - Returns and finding a receipt ROUGH DRAFT : return.md
#   - How to find next APPT date
#   - Workorder
#   - How to create a work order
#   - Creating a work order for a repair
#   - Counting out
#   - Opening register procedures
#   - Using Square - how to ring people up and reconcile the payments in LS



# - Resources:
#    Employee handbook 
#    Attendance - shift start & end, calling out, scheduling time off
#    Breaks
#    Employee purchases
#    Dress code
#    After hours policy
#    PTO and vacation policy



theme: readthedocs
plugins:
   - glightbox:
      zoomable: true